### ISSUE TITLE
Progress always on newline, not overwriting same line?

### ISSUE THREAD

**Issue by ckcollab** [WoLpH/python-progressbar#36]
First of all: thanks for all the development on this! I'm getting a small problem with the output being on newlines. Not sure if this is intended behavior, I assumed the text would be updated inline, but instead I get progress updates on new lines:
```bash
1
  0%|                                                                          |2
  0%|                                                                          |3
  0%|                                                                          |4
  1%|                                                                          |5
  1%|                                                                          |6
  1%|#                                                                         |7
  1%|#                                                                         |8
  2%|#                                                                         |9
  2%|#                                                                         |10
  2%|#                                                                         |11
```

Here's my code:
```python
    progress_bar = ProgressBar(max_value=image_count).start()
    for root, _, files in os.walk(directory):
        for file_name in files:
            loop_counter += 1
            progress_bar.update(loop_counter)
            ...
    print("Done processing images!")
    progress_bar.finish()
```

**Comment by WoLpH** [comment]
This is generally caused by a print statement somewhere in your code. By specifying `redirect_stdout` and/or `redirect_stderr` this should be fixed. Note that the previous version had a bug in that code so I would recommend updating to the latest version (3.4.0 or higher) before trying.

http://progressbar-2.readthedocs.org/en/latest/usage.html#combining-progressbars-with-print-output

Example:
```
import time
import progressbar

bar = progressbar.ProgressBar(redirect_stdout=True)
for i in range(100):
    print 'Some text', i
    time.sleep(0.1)
    bar.update(i)
```

**Comment by ckcollab** [comment]
You're right, I left a print in there, thanks so much for the quick fix!

**Comment by trianglesis** [comment]
I still having this issue:

/ Checking syntax. Elapsed Time: 0:00:13.                                      2017-09-25 15:48:34,077 INFO     Build OK: Syntax: PASSED!

Printing on the same line.
When:
            bar = progressbar.ProgressBar(widgets=widgets,
                                          max_value=progressbar.UnknownLength,
                                          redirect_stdout=True,
                                          redirect_stderr=True
                                          )
I tried both true, each true and both false. And this does not help.

**Comment by trianglesis** [comment]
Now fixed:

```
progressbar.streams.flush()
progressbar.streams.wrap_stdout()
redirect_stdout=True
bar.finish()
```
This options end string normally.

**Comment by namekkozZ** [comment]
@trianglesis i have same issue, can you show me the complete code?

**Comment by trianglesis** [comment]
It's abandoned package, but progress bar was implemented here:
@namekkozZ https://github.com/trianglesis/BMC_TPL_IDE/blob/master/bmc_tplpre/check_ide/syntax_checker.py
