### ISSUE TITLE
signal.SIGWINCH does not exist on Windows

### ISSUE THREAD

**Issue by pganssle** [WoLpH/python-progressbar#39]
Version 3.4.1 of progressbar2 seems to be completely broken on Windows, because it is calling `signal.SIGWINCH`, which is apparently not available on Windows.

```python
>>> import progressbar
>>> pb = progressbar.ProgressBar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\progressbar\bar.py", line 167, in __init__
    StdRedirectMixin.__init__(self, **kwargs)
  File "C:\Python34\lib\site-packages\progressbar\bar.py", line 75, in __init__
    super(StdRedirectMixin, self).__init__(**kwargs)
  File "C:\Python34\lib\site-packages\progressbar\bar.py", line 57, in __init__
    signal.signal(signal.SIGWINCH, self._handle_resize)
AttributeError: 'module' object has no attribute 'SIGWINCH'
```

Tested on Python 2.7.10 and Python 3.4.3 on Windows 7. Also tested in Anaconda and Anaconda3 (python 2.7.10 and 3.4.3 respectively).

**Comment by WoLpH** [comment]
Hmm, good point. Didn't think about that. I'll try to work around the issue for windows.

**Comment by WoLpH** [comment]
I've fixed the issue by defaulting to only a single size detection if the signals go wrong, a new release will be pushed out soon :)

**Comment by pganssle** [comment]
Cool, sorry, I forgot to test this out when I was at work (running Linux at home so it's less convenient to spin up virtual machines and whatnot). I'll give it a shot tomorrow.

**Comment by dofine** [comment]
Problem still exists for me... Using version 3.5.0 and Python 2.7.10 on Windows 7.

**Comment by WoLpH** [comment]
Can you show a full stacktrace? Assuming you are running the updated
version this should not be possible anymore.

**Comment by bastelflp** [comment]
Problem still exists for me as well, installed progressbar via ```python setup.py install``` from git repo tag [v3.5.0](https://github.com/WoLpH/python-progressbar/tree/v3.5.0) and tested with the following script:

```
import progressbar
import time

with progressbar.ProgressBar(max_value=10) as progress:
    for i in range(10):
        time.sleep(0.001)
        progress.update(i)
```

System:
```
Python 3.4.3 |Anaconda 2.4.0 (64-bit)| (default, Oct 28 2015, 15:59:18) [MSC v.1600 64 bit (AMD64)] on win32
```

Backtrace:
```
Traceback (most recent call last):
  File "progress_test.py", line 4, in <module>
    with progressbar.ProgressBar(max_value=10) as progress:
  File "C:\Users\usr\Anaconda\envs\py34\lib\site-packages\progressbar2-3.5.0-py3.4.egg\progressbar\bar.py", line 173, in __init__
    ResizableMixin.__init__(self, **kwargs)
  File "C:\Users\usr\Anaconda\envs\py34\lib\site-packages\progressbar2-3.5.0-py3.4.egg\progressbar\bar.py", line 57, in __init__
    signal.signal(signal.SIGWINCH, self._handle_resize)
AttributeError: 'module' object has no attribute 'SIGWINCH'
```

**Comment by ritave** [comment]
Confirming the issue, same as @bastelflp

**Comment by WoLpH** [comment]
It's just silliness on my end... guess I was tired when writing that code.

The try/except all looks good, except I apparently kept the `raise` in there... I'll push out a fix today :)
https://github.com/WoLpH/python-progressbar/blob/develop/progressbar/bar.py#L54-L60
```
            try:
                self._handle_resize()
                import signal
                signal.signal(signal.SIGWINCH, self._handle_resize)
                self.signal_set = True
            except:  # pragma: no cover
                raise
```

**Comment by WoLpH** [comment]
It should be fixed in https://github.com/WoLpH/python-progressbar/tree/v3.5.1

Sorry about all the silly bugs lately, I'm just a bit overloaded with work
